[package]
name = "cesride-wasm"
version = "0.1.0"
authors = ["The wasm-bindgen Developers"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]
tmp_dev = []

[dependencies.cesride_core]
path = '..'
package = "cesride"

[dependencies]
wasm-bindgen = "0.2.84"
js-sys = '0.3'
serde_json = "1.0"